name: CI - Code Coverage Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build and run tests with JaCoCo
        run: mvn clean verify jacoco:report

      - name: Check code coverage using CSV
        run: |
          echo "Checking code coverage from CSV..."
          CSV_FILE="target/site/jacoco/jacoco.csv"

          if [ ! -f "$CSV_FILE" ]; then
            echo "❌ CSV file not found!"
            exit 1
          fi

          # Extract coverage from first actual class entry (skip header)
          LINE=$(tail -n +2 "$CSV_FILE" | head -n 1)

          MISSED=$(echo "$LINE" | cut -d',' -f4)
          COVERED=$(echo "$LINE" | cut -d',' -f5)

          TOTAL=$((MISSED + COVERED))

          if [ "$TOTAL" -eq 0 ]; then
            PERCENT=0
          else
            PERCENT=$(( 100 * COVERED / TOTAL ))
          fi

          echo "🟡 Code Coverage: $PERCENT%"

          if [ "$PERCENT" -lt 80 ]; then
            echo "❌ Code coverage ($PERCENT%) is below threshold (80%)"
            exit 1
          else
            echo "✅ Code coverage check passed: $PERCENT%"
          fi
